### ISSUE TITLE
Sponsor Landing Page: Wireframe

### ISSUE THREAD

**Issue by benglass** [burlingtoncode/burlingtoncode.org#3]
@AndrewSepic can you upload the screenshot of the whiteboard?

**Comment by AndrewSepic** [comment]
![wireframe-mock](https://cloud.githubusercontent.com/assets/1304666/14289264/04e30436-fb28-11e5-8c04-b62331d841ad.png)

**Comment by benglass** [comment]
@jhoguet @AndrewSepic 

I put together a wireframe based on this. Started to play around with some copy, feedback welcome.

[Burlington-Code-Sponsor-Landing-Wireframe-v1.pdf](https://github.com/burlingtoncode/burlingtoncode.org/files/205663/Burlington-Code-Sponsor-Landing-Wireframe-v1.pdf)

Didn't know github supported file uploads, cool.

**Comment by AndrewSepic** [comment]
@benglass & @jhoguet  I see in the wireframe from our meeting we had 'member logos' as the section beneath our Hero area, but I think there was some discussion about how we'd hack together logos for all the meetups.  I'm seeing there might be some issues here with sustainability in the design if we have some meetups without logos, some meetups are not actually their own Meetup group (ie: Burlington JS) and other meetups may be added or pass away (Meteor Burlington or others).  I'm trying to think of the most visually elegant solution, which can respond to this.  

If we don't feel it's necessary that the meetups themselves have a lot of visual weight, they could just be listed in a <ul></ul> in the 'At a Glance' block.  

I'll digest this for a bit...

**Comment by benglass** [comment]
@AndrewSepic One possible solution we discussed there was simply using the language specific logo which works for JS, Python and Wordpress but not for Data Scientists although it looks like they have a logo

![global_439576054](https://cloud.githubusercontent.com/assets/1964631/14583748/5d9b25ac-03f9-11e6-867f-028497af54eb.jpeg)

**Comment by benglass** [comment]
Some other logos...

![wordpress](https://cloud.githubusercontent.com/assets/1964631/14583760/d5b8f17c-03f9-11e6-8457-53a45f65427e.jpg)

![python-logo](https://cloud.githubusercontent.com/assets/1964631/14583761/d8e442fc-03f9-11e6-85d1-190d9e7ed9a0.png)

![learn-javascript](https://cloud.githubusercontent.com/assets/1964631/14583762/db856b58-03f9-11e6-8fa9-b68012f5b7ba.png)

![logo_javascript](https://cloud.githubusercontent.com/assets/1964631/14583763/ddd13658-03f9-11e6-8f25-83bf873fa598.png)

**Comment by jhoguet** [comment]
we did say that industry logos was an option - but I am now feeling more strongly that we should not. 

I think we should skip logos for user groups for now. 

It isn't really something that we (Burlington Code) should be providing. In other words, in spirit with Burlington Code not trying to interfere with a User Group's identity, we should not take any proactive action to help build their identity (like using industry logos when they don't have a logo). 

Given that the source will be in github it will be easy to add logos for those that request it. 

That is my 2 cents...

**Comment by zevaverbach** [comment]
This seems fairly resolved, no?  Anyone who's been on the project more than an hour want to close this?
