### ISSUE TITLE
Sponsor Landing Page: Copy

### ISSUE THREAD

**Issue by benglass** [burlingtoncode/burlingtoncode.org#5]

**Comment by AndrewSepic** [comment]
Here's the notes from last night.
![howbc-helps](https://cloud.githubusercontent.com/assets/1304666/14289333/4ed3fa8c-fb28-11e5-87d4-843f59ef5817.png)
![goal-content](https://cloud.githubusercontent.com/assets/1304666/14289335/512aed4a-fb28-11e5-9c4e-f37a3a868e80.png)

**Comment by jhoguet** [comment]
I am going to close this since this has evolved into the mockup and no longer has value
