### ISSUE TITLE
Burlington Code Logo or Wordmark

### ISSUE THREAD

**Issue by benglass** [burlingtoncode/burlingtoncode.org#6]

**Comment by AndrewSepic** [comment]
Hi @benglass & @jhoguet,  
Here's a PDF with some logo drafts I've mocked up for Burlington Code.  They are the result of some mind-mapping  and then a 2-3 pages of sketches.  I'd love to hear from you guys and see what you think about the potential directions they offer.  Once we narrow that down, I'll finish with adding color and final details and then move onto the landing page design.  

p.s. Sorry for the relative delay in getting these done,  I've had to give my MacBook over to Small Dog for logic board repairs and it's taken an undesirably longer than expected time
[BC-Logo-drafts.pdf](https://github.com/burlingtoncode/burlingtoncode.org/files/222402/BC-Logo-drafts.pdf)
 to get my working environment set up on a temp computer.

**Comment by jhoguet** [comment]
wow @AndrewSepic these are awesome. 

My vote is for no 2

**Comment by benglass** [comment]
@AndrewSepic They look great, I like both 1 and 2. Like the condensed/tech-y font face in number 1, but like the simplicity of number 2.

Sorry to hear you've been having computer troubles.. mac repairs are a hassle

**Comment by AndrewSepic** [comment]
Ok @jhoguet & @benglass I went with Option no. 2 and tried a bunch of color options.  Here's my favorite scheme with 3 variations, placed vertically in my order of preference.  My designer side likes the subtlety of the light grey of Burlington in the top one best, but I also know many people don't like values which are so close to white (causing eye strain perhaps). 

If you have any clear one which speaks to you most, let me know!  I'll move on to the web design after this.  Thanks for your patience!

![logo-color-options](https://cloud.githubusercontent.com/assets/1304666/14825872/9efb6b4e-0ba9-11e6-9358-ecb529580a4a.jpg)

**Comment by benglass** [comment]
@AndrewSepic Looks great with color, specifically like numbers 2 and 3, it feels like the burlington gets a little lost in the first one.

**Comment by jhoguet** [comment]
# 3 gets my vote - looking great

**Comment by AndrewSepic** [comment]
10 4!  I'll let the web design make the final decision between 2 & 3 then.
